### ISSUE TITLE
GitHub Markdown compatibility

### ISSUE THREAD

**Issue by eecs441staff** [eecs485staff/primer-spec#58]
Primer-spec doesn’t recognize ‘\’ as line-break marker, as GitHub Markdown does, requiring use of double spaces instead.

**Comment by seshrs** [comment]
Thanks for reporting @eecs441staff! I dug a bit deeper, and I have some good news, some bad news and a potential alternative.

**Good news:** It's very easy to enable GitHub Flavored MarkDown (GFM) for your site! Simply add a `markdown: GFM` option to your `_config.yml` so that it looks something like this:
```yml
remote_theme: eecs485staff/primer-spec
plugins:
    - jekyll-remote-theme

# The default MarkDown processor for Jekyll is actually 'kramdown'. Change to GFM if you prefer.
markdown: GFM
```

**Bad news:** If you make the change above, *you will not be able to preview your site locally*. It looks like Jekyll 3.8 has some bugs with the GFM parser dependency. It's fixed in Jekyll 4, but GitHub Pages hasn't upgraded their version of Jekyll yet. 😢 

---

**Alternative:** I know this isn't a great alternative, but another way to force a line-break is to add two spaces at the end of the line. For example:
```markdown
This is on line 1
and this is a continuation of that line. But if you add two spaces -->  
then this line gets broken!
```

---

I will update the Advanced Usage docs to explain how to use GFM on a Primer Spec site.

**Comment by eecs441staff** [comment]
@seshrs the following:
```yml
remote_theme: eecs485staff/primer-spec
plugins:
    - jekyll-remote-theme
markdown: GFM
```
did it for me: `\` now works as line-break when viewed on GitHub Pages.

Both Chrome and Safari immediately download my .md files, so I never had local preview anyway.  Thanks!
